services:
  redis:
    image: redis:7-alpine
    container_name: jarvis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jarvis-network

  jarvis-whatsapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jarvis-whatsapp-llm
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      # Configurações LLM
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://192.168.15.31:11435}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3:latest}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-500}
      - LLM_TIMEOUT=${LLM_TIMEOUT:-30}
      # Logs detalhados
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
    networks:
      - jarvis-network

  # Opcional: Ollama local (se quiser rodar localmente)
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: jarvis-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0
  #   restart: unless-stopped
  #   networks:
  #     - jarvis-network

volumes:
  redis_data:
    driver: local
  # ollama_data:
  #   driver: local

networks:
  jarvis-network:
    driver: bridge